### ISSUE TITLE
建议：后台管理Meta关键词，通过placeholder添加指导意见

### ISSUE THREAD

**Issue by pacez** [innocms/innocms#5]
建议：后台管理Meta关键词，通过placeholder添加指导意见。比如：
 1. 确信使用的关键词出现在网页文本中
 2. 不要重复使用关键词
 3. 一个网页的关键词标签里应该包含 3-5 个最重要的关键词，不要超过 5 个。

**Comment by yushine** [comment]
好的，后台表单每个地方都应该有，尽量让用户不离开页面、不用去看使用文档就能明白是做什么的。
